# Generated by Django 3.2.1 on 2021-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='miner_type',
            field=models.CharField(choices=[('heuristics_miner', 'heuristics_miner'), ('alpha_miner', 'alpha_miner')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
