# Generated by Django 3.2.1 on 2021-05-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0002_auto_20210505_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='image',
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='miner_type',
            field=models.CharField(choices=[('heuristics_miner', 'heuristics miner'), ('alpha_miner', 'alpha miner')], max_length=100),
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_logs.csvfile')),
            ],
        ),
    ]
