# Generated by Django 3.2.1 on 2021-05-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0003_auto_20210511_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimage',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_logs.csvfile'),
        ),
    ]
